[workspace]
resolver = "2"
members = [
  "packages/ipc-client",
  "packages/ipc-server",
  "packages/watcher",
  "packages/wm",
]

[workspace.dependencies]
regex = "1"
tokio = { version = "1", features = ["full"] }
windows = { version = "0.52", features = [
  "implement",
  "Win32_System_Com",
  "Win32_UI_Shell_Common",
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_System_RemoteDesktop",
  "Win32_System_Threading",
  "Win32_UI_Accessibility",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Shell",
  "Win32_UI_Shell_Common",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_SystemServices",
] }
