[workspace]
resolver = "2"
members = ["packages/*"]
default-members = ["packages/wm", "packages/watcher"]

[workspace.dependencies]
anyhow = { version = "1", features = ["backtrace"] }
serde_json = { version = "1", features = ["raw_value"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
