[workspace]
resolver = "2"
members = ["packages/*"]
default-members = ["packages/wm"]

[workspace.dependencies]
anyhow = "1"
regex = "1"
tokio = { version = "1", features = ["full"] }
windows = { version = "0.52", features = [
  "implement",
  "Win32_Foundation",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_Gdi",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_System_LibraryLoader",
  "Win32_System_Registry",
  "Win32_System_RemoteDesktop",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
  "Win32_UI_Accessibility",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_Ime",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Shell_Common",
  "Win32_UI_TextServices",
  "Win32_UI_WindowsAndMessaging",
] }
