[package]
name = "watcher"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "watcher"
path = "src/main.rs"

[build-dependencies]
tauri-winres = { workspace = true }

[dependencies]
wm = { path = "../wm" }

anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
