[package]
name = "watcher"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "watcher"
path = "src/main.rs"

[dependencies]
wm = { path = "../wm" }

anyhow = { workspace = true }
tokio = { workspace = true }
serde_json = "1.0.117"
