[package]
name = "wm"
version = "0.0.0"
description = "GlazeWM is a tiling window manager for Windows inspired by i3 and Polybar."
repository = "https://github.com/glzr-io/glazewm"
license = "GPL-3"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "wm"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
enum_dispatch = "0.3"
enum-as-inner = "0.6"
futures-util = "0.3"
home = "0.5"
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
regex = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = "0.21"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
windows = { workspace = true }
