name: Lint check

on: push

jobs:
  lint-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248
        with:
          toolchain: nightly
          components: rustfmt

      - uses: swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894

      - name: Check formatting
        run: cargo fmt --check

      - name: Check build
        run: cargo build --locked
