name: Lint check

on: push

jobs:
  lint-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
        with:
          toolchain: nightly
          components: rustfmt

      - uses: swatinem/rust-cache@9bdad043e88c75890e36ad3bbc8d27f0090dd609

      - name: Check formatting
        run: cargo fmt --check

      - name: Check build
        run: cargo build --locked
