name: Package

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download executables
        uses: actions/download-artifact@v4
        with:
          name: executables-*
          path: tmp/

      - name: Download Zebar installers
        run: |
          $latestRelease = 'https://api.github.com/repos/glzr-io/zebar/releases/latest'
          $latestInstallers = Invoke-RestMethod $latestRelease | % assets | ? name -like "*.msi"
          $latestInstallers | % { Invoke-WebRequest $_.browser_download_url -OutFile $_.name }

      - name: Install WiX and its extensions
        run: |
          dotnet tool install --global wix --version 5.0.0
          wix extension add WixToolset.UI.wixext/5 WixToolset.Util.wixext/5 WixToolset.BootstrapperApplications.wixext/5

      - name: Create MSI installer (x64)
        run: |
          wix build -arch "x64" -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext \
            -out "./tmp/installer-x64.msi" "./resources/standalone.wxs"

      - name: Create MSI installer (arm64)
        run: |
          wix build -arch "arm64" -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext \
            -out "./tmp/installer-arm64.msi" "./resources/standalone.wxs"

      - name: Create universal installer
        run: |
          wix build -arch "x64" -ext WixToolset.BootstrapperApplications.wixext \
            -out "./tmp/installer-universal.exe" "./resources/bundle.wxs"

      - uses: actions/upload-artifact@v4
        with:
          name: installers
          if-no-files-found: error
          path: tmp/installer-*
