name: Package

on:
  workflow_call:

jobs:
  next-version:
    uses: semantic-release-action/next-release-version/.github/workflows/next-release-version.yml@3c2d88ce0390012bac0b8383059a0b67d2594dc1

  package:
    needs: [next-version]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@be73d7920c329f220ce78e0234b8f96b7ae60248
        with:
          toolchain: nightly
          targets: x86_64-pc-windows-msvc,aarch64-pc-windows-msvc

      - uses: swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894
        with:
          shared-key: ${{ hashFiles('Cargo.lock') }}

      - name: Run packaging script
        run: |
          ./resources/scripts/package.ps1 -VERSION_NUMBER ${{ needs.next-version.outputs.new-release-version }}

      - uses: actions/upload-artifact@v4
        with:
          name: installers
          if-no-files-found: error
          path: out/installer-*
