name: Release

on:
  workflow_dispatch:
    inputs:
      draft-release:
        type: boolean
        default: true
        description: Whether to publish the release as a draft.

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: release

jobs:
  package:
    uses: ./.github/workflows/package.yaml

  release:
    needs: [package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download installers
        uses: actions/download-artifact@v4
        with:
          name: installers
          path: tmp/

      - name: Semantic release
        uses: glzr-io/actions/semantic-release@main
        with:
          gh-publish: true
          gh-draft-release: ${{ inputs.draft-release }}
          gh-token: ${{ github.token }}
          gh-assets: |
            [
              {
                "path": "tmp/installer-universal",
                "name": "glazewm-${nextRelease.gitTag}",
                "label": "${nextRelease.gitTag} Installer (recommended)"
              },
              {
                "path": "tmp/installer-x64",
                "name": "glazewm-x64-${nextRelease.gitTag}",
                "label": "${nextRelease.gitTag} Installer (standalone x64)"
              },
              {
                "path": "tmp/installer-arm64",
                "name": "glazewm-arm64-${nextRelease.gitTag}",
                "label": "${nextRelease.gitTag} Installer (standalone arm64)"
              }
            ]
