name: Release

on:
  workflow_dispatch:
    inputs:
      draft-release:
        type: boolean
        default: false
        description: Whether to publish the release as a draft.

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: release

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  pre-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts (x64)
        uses: actions/download-artifact@v4
        with:
          name: installer-x86_64-pc-windows-msvc
          path: tmp/installer-x64

      - name: Download artifacts (arm64)
        uses: actions/download-artifact@v4
        with:
          name: installer-aarch64-pc-windows-msvc
          path: tmp/installer-arm64

      - uses: glzr-io/actions/semantic-release@main
        with:
          gh-publish: true
          gh-draft-release: ${{ inputs.draft-release }}
          gh-token: ${{ github.token }}
          gh-assets: |
            [
              {
                "path": "tmp/installer-x64",
                "name": "glazewm_x64_${nextRelease.gitTag}"
              },
              {
                "path": "tmp/installer-arm64",
                "name": "glazewm_arm64_${nextRelease.gitTag}"
              }
            ]
